name: Export Google Sheet to HTML

on:
  push:
    branches:
      - main  # Trigger on changes to the `main` branch
  schedule:
    - cron: '0 * * * *'  # Run every hour on the hour

jobs:
  download-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Download Google Sheets Export Zip
      run: |
        curl -L -o export.zip "https://docs.google.com/spreadsheets/d/13I_KQ4usdABOUNE-BkHhORcXaCwDpq7y5ziBq86lC5U/export?format=zip&id=13I_KQ4usdABOUNE-BkHhORcXaCwDpq7y5ziBq86lC5U"

    - name: Extract Testbed.html from the zip file
      run: |
        unzip export.zip "Testbed.html" -d extracted

    - name: Move Testbed.html to the root of the gh-pages branch
      run: |
        mv extracted/Testbed.html .

    - name: Set up GitHub Pages branch (gh-pages)
      run: |
        git fetch origin gh-pages:gh-pages || git checkout --orphan gh-pages  # Ensure gh-pages branch exists
        git checkout gh-pages
        git rm -rf .  # Remove all existing files in gh-pages (optional)
        mv Testbed.html .  # Move Testbed.html to the root of the gh-pages branch
        git add Testbed.html
        git commit -m "Update Testbed.html"
        git push origin gh-pages
