name: Export Google Sheet to HTML

on:
  push:
    branches:
      - main  # Trigger on changes to the `main` branch
  schedule:
    - cron: '0 * * * *'  # Run every hour on the hour

jobs:
  download-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python (for downloading and extraction)
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install required dependencies
      run: |
        pip install requests zipfile

    - name: Download Google Sheets Export Zip
      run: |
        curl -L -o export.zip "https://docs.google.com/spreadsheets/d/13I_KQ4usdABOUNE-BkHhORcXaCwDpq7y5ziBq86lC5U/export?format=zip&id=13I_KQ4usdABOUNE-BkHhORcXaCwDpq7y5ziBq86lC5U"

    - name: Extract Testbed.html from the zip file
      run: |
        unzip export.zip "Testbed.html" -d extracted

    - name: Move Testbed.html to the root directory
      run: |
        mv extracted/Testbed.html .

    - name: Commit and push the Testbed.html to the main branch
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add Testbed.html
        git commit -m "Update Testbed.html"
        git push origin main
