name: Export Google Sheet to HTML

on:
  push:
    branches:
      - main  # Trigger on changes to the `main` branch
  schedule:
    - cron: '0 * * * *'  # Run every hour on the hour

jobs:
  download-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Download Google Sheets Export Zip
      run: |
        curl -L -o export.zip "https://docs.google.com/spreadsheets/d/13I_KQ4usdABOUNE-BkHhORcXaCwDpq7y5ziBq86lC5U/export?format=zip&id=13I_KQ4usdABOUNE-BkHhORcXaCwDpq7y5ziBq86lC5U"

    - name: Extract Testbed.html from the zip file
      run: |
        unzip export.zip "Testbed.html" -d extracted

    - name: Move Testbed.html to assets directory
      run: |
        mkdir -p assets  # Ensure the assets folder exists
        mv extracted/Testbed.html assets/testbed.html  # Move the HTML to assets/testbed.html
        mv extracted/resources/sheet.css assets/resources/sheet.css  # Move the CSS to assets/resources/sheet.css

    - name: Commit and push the Testbed.html to the main branch
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add assets/testbed.html  # Add the HTML file in assets
        git commit -m "Update Testbed.html in assets"
        git push origin main  # Push to the main branch
