name: Export Google Sheet to HTML

on:
  push:
    branches:
      - main  # Trigger on changes to the `main` branch
  schedule:
    - cron: '0 0 * * *'  # Run once a day at midnight UTC

jobs:
  download-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Download Google Sheets Export Zip
      run: |
        curl -L -o export.zip "https://docs.google.com/spreadsheets/d/13I_KQ4usdABOUNE-BkHhORcXaCwDpq7y5ziBq86lC5U/export?format=zip&id=13I_KQ4usdABOUNE-BkHhORcXaCwDpq7y5ziBq86lC5U"

    - name: Extract Testbed.html and sheet.css from the zip file
      run: |
        unzip export.zip "Testbed.html" -d extracted
        unzip export.zip "resources/sheet.css" -d extracted

    - name: Move Testbed.html to assets directory
      run: |
        mkdir -p assets  # Ensure the assets folder exists
        mv extracted/Testbed.html assets/testbed.html  # Move Testbed.html to assets/testbed.html

    - name: Move sheet.css to assets/resources directory
      run: |
        mkdir -p assets/resources  # Ensure the resources folder exists within assets
        mv extracted/resources/sheet.css assets/resources/sheet.css  # Move sheet.css to assets/resources/sheet.css

    - name: Commit and push the Testbed.html and sheet.css to the main branch
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add assets/testbed.html assets/resources/sheet.css  # Add both files
        git commit -m "Update Testbed.html and sheet.css in assets"
        git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/bassamlab/testbeds-survey.git main
